[pytest]
addopts = -v -s --alluredir=report/allure-results --clean-alluredir
testpaths = testcase
pythonpath = .
markers =
    ui: UI 自动化测试用例（通用标记）
    web: Web 端用例
    android: Android 端用例
    ios: IOS 端用例
