server {
    listen 8080;
    server_name _;
    root /reports/workspace/UITest-CI/report/ui-html;
    index index.html;
    server_tokens off;
    autoindex off;
    disable_symlinks on;
    add_header X-Content-Type-Options nosniff always;
    location / {
        try_files $uri $uri/ =404;
    }
}
